name: Publish API Docs

on:
  release:
    types:
      - published
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: temurin

jobs:
  deploy:

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.3.0

      - name: Generate Dokka Site
        run: |-
          ./gradlew knit docs:classes docs:knitCheck dokkaGenerate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/dokka/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
